### ISSUE TITLE
Upstream qarminer

### ISSUE THREAD

**Issue by jvoisin** [qarmin/Qarminer#31]
Do you have any plans to upstream qarminer into godot and/or oss-fuzz?

**Comment by qarmin** [comment]
Not really
- repo uses GDScript and Godot runs it as normal project(which is quite slow), so cannot be used directly in oss-fuzz which require C/C++ integration with project because Godot is not enough modular to only test certain functions from C/C++ and needs other parts of engine to be properly initialized to run properly.
- already part stripped version of fuzzer is used in Godot CI as test project to check for memory corruption, leaks, crashes but only with  same set of parameters(to be able to easily reproduce problems) - https://github.com/godotengine/regression-test-project/.
Theoretically, the project could try to be added the official Godot repo, but it consumes a lot of CI time(for me it's not a problem, but Godot tries to reduce these times as much it is possible) but above all, Godot's developers are unlikely to see a special need for it, since it usually detects quite unusual problems and the most basic and critical ones are detected by the project in CI
